//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMLASTMAY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Order = new HashSet<Order>();
        }
    
        public string ClientCode { get; set; }
        public string ClientSurname { get; set; }
        public string ClientFirstName { get; set; }
        public string ClientPatronymic { get; set; }
        public string ClientPassportSeries { get; set; }
        public string ClientPassportNumber { get; set; }
        public Nullable<System.DateTime> ClientDateBirthday { get; set; }
        public string ClientIndex { get; set; }
        public string ClientCity { get; set; }
        public string ClientStreet { get; set; }
        public string ClientHouse { get; set; }
        public int ClientFlat { get; set; }
        public string ClientEmail { get; set; }
        public string ClientPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
