//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMLASTMAY
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpoyeeHistory
    {
        public int HistoryId { get; set; }
        public string EmployeeLogin { get; set; }
        public bool LoginStatus { get; set; }
        public System.DateTime EmployeeDataLogin { get; set; }
    }
}
