//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMLASTMAY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Service = new HashSet<Service>();
        }
    
        public int OrderID { get; set; }
        public string OrderCode { get; set; }
        public System.DateTime OrderDateCreate { get; set; }
        public System.TimeSpan OrderTimeCreate { get; set; }
        public string ClientCode { get; set; }
        public int OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderDateClose { get; set; }
        public int OrderTimeRent { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual OrderStatus OrderStatus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service { get; set; }
    }
}
